export type Locale = 'en' | 'pt-BR';

export const copy = {
  en: {
    language: 'Language', home: 'Home',
    eyebrow: 'A daily reading reset',
    title: 'Stay informed without getting lost in the feed',
    intro: 'Too many tabs. Too many takes on the same story. Too little time to find what actually matters.',
    detail: 'Tech Digest does the sorting for you: a short, thoughtful selection of software engineering and technology reads, delivered every morning.',
    heroNote: 'One email. Up to eight links. A clearer start to your day.',
    nextEdition: 'Next edition', everyDay: 'Every day at 7:00 AM, Brasília time',
    countdown: 'Time until the next edition', hours: 'hours', minutes: 'minutes', seconds: 'seconds',
    cardTitle: 'Make room for better reading.',
    cardDescription: 'Get the next edition straight to your inbox.',
    email: 'Email address', placeholder: 'you@example.com', subscribe: 'Get the digest', subscribing: 'Subscribing…',
    subscribeSuccess: 'You’re on the list. See you in your inbox.',
    invalidEmail: 'Enter a valid email address.',
    rateLimited: 'Too many attempts. Please try again later.',
    unavailable: 'The service is unavailable right now. Please try again later.',
    privacy: 'No account. No clutter. Unsubscribe with one click in any email.',
    from: 'A project by João Coelho',
    unsubscribeTitle: 'Stop receiving Tech Digest?', unsubscribeDetail: 'You can leave the list at any time.',
    confirm: 'Confirm unsubscribe', confirming: 'Unsubscribing…',
    unsubscribeSuccess: 'You’re unsubscribed. You won’t receive the next Tech Digest.',
    invalidToken: 'This unsubscribe link is not valid.', back: 'Back to Tech Digest',
    painLabel: 'The problem',
    painTitle: 'Keeping up should not be a second job',
    painIntro: 'The interesting ideas are out there. Finding them between repeated headlines, endless feeds, and saved links takes work.',
    painItems: [
      { number: '01', title: 'The feed never ends', description: 'New posts arrive faster than anyone can read them.' },
      { number: '02', title: 'The same story repeats', description: 'Five open tabs can still leave you with one new idea.' },
      { number: '03', title: 'The good links get lost', description: 'The article worth your time disappears into a pile of “read later.”' },
    ],
    answerTitle: 'A smaller list. A better signal.',
    answerDescription: 'Open one email and get straight to the reads worth considering. No scrolling to find the point.',
    sampleLabel: 'In your inbox', sampleTitle: 'See what makes the cut',
    sampleIntro: 'An illustrative edition showing how the email arrives in your inbox. The selection changes every day.',
    sampleAsideTitle: 'The good links, at a glance.',
    sampleAsideDescription: 'A short list with the source and subject of each story, so you can choose what to open.',
    sampleStamp: 'SEP 23',
    sampleEditionTitle: 'Technology worth your time.',
    sampleEditionDate: 'Wednesday, September 23, 2026',
    sampleEditionCount: '3 selected stories from the last 24 hours',
    sampleArticleMeta: [
      'The Pragmatic Engineer · Sep 22',
      'Simon Willison · Sep 22 · AI models',
      'SQLite · Sep 23 · Databases · Systems',
    ],
    sampleLeadTopic: 'Software engineering',
    sampleCurated: 'Curated by João Coelho',
    sampleWebsite: 'Website',
    sampleUnsubscribe: 'Unsubscribe',
    processLabel: 'How it works', processTitle: 'Curated before it reaches you',
    processIntro: 'The digest follows a simple path from trusted sources to a useful morning email.',
    steps: [
      { title: 'Look broadly', description: 'Selected RSS and Atom feeds are checked throughout the day.' },
      { title: 'Keep the signal', description: 'Articles are assessed for relevance, and overlapping coverage is removed.' },
      { title: 'Send the essentials', description: 'Up to eight links arrive together at 7:00 AM, Brasília time.' },
    ],
    finalLabel: 'Tomorrow starts here', finalTitle: 'Less searching. More discovering.',
    finalDescription: 'Start your day with a short list of ideas worth opening.',
    finalAction: 'Get the next edition',
  },
  'pt-BR': {
    language: 'Idioma', home: 'Início',
    eyebrow: 'Uma pausa diária para ler melhor',
    title: 'Atualize-se sem se perder no feed',
    intro: 'Abas demais. Opiniões demais sobre a mesma notícia. Tempo de menos para encontrar o que realmente importa.',
    detail: 'O Tech Digest faz a triagem para você: uma seleção curta e cuidadosa de leituras sobre engenharia de software e tecnologia, entregue toda manhã.',
    heroNote: 'Um e-mail. Até oito links. Um começo de dia mais claro.',
    nextEdition: 'Próxima edição', everyDay: 'Todos os dias às 7h, horário de Brasília',
    countdown: 'Tempo até a próxima edição', hours: 'horas', minutes: 'minutos', seconds: 'segundos',
    cardTitle: 'Abra espaço para leituras melhores.',
    cardDescription: 'Receba a próxima edição direto no seu e-mail.',
    email: 'Endereço de e-mail', placeholder: 'voce@exemplo.com', subscribe: 'Receber o digest', subscribing: 'Inscrevendo…',
    subscribeSuccess: 'Inscrição confirmada. Até o próximo e-mail.',
    invalidEmail: 'Digite um endereço de e-mail válido.',
    rateLimited: 'Muitas tentativas. Tente novamente mais tarde.',
    unavailable: 'O serviço está indisponível agora. Tente novamente mais tarde.',
    privacy: 'Sem conta. Sem excesso. Cancele com um clique em qualquer e-mail.',
    from: 'Um projeto de João Coelho',
    unsubscribeTitle: 'Parar de receber o Tech Digest?', unsubscribeDetail: 'Você pode sair da lista a qualquer momento.',
    confirm: 'Confirmar cancelamento', confirming: 'Cancelando…',
    unsubscribeSuccess: 'Inscrição cancelada. Você não receberá o próximo Tech Digest.',
    invalidToken: 'Este link de cancelamento não é válido.', back: 'Voltar ao Tech Digest',
    painLabel: 'O problema',
    painTitle: 'Se manter atualizado não deveria ser um segundo trabalho',
    painIntro: 'As ideias interessantes estão por aí. Encontrá-las entre notícias repetidas, feeds infinitos e links salvos dá trabalho.',
    painItems: [
      { number: '01', title: 'O feed não acaba', description: 'Novos posts chegam mais rápido do que qualquer pessoa consegue ler.' },
      { number: '02', title: 'A mesma história se repete', description: 'Cinco abas abertas ainda podem trazer só uma ideia nova.' },
      { number: '03', title: 'Os bons links se perdem', description: 'O artigo que vale seu tempo some na pilha do “ler depois”.' },
    ],
    answerTitle: 'Uma lista menor. Um sinal melhor.',
    answerDescription: 'Abra um e-mail e vá direto às leituras que merecem atenção. Sem rolar a tela para encontrar o ponto.',
    sampleLabel: 'Na sua caixa de entrada', sampleTitle: 'Veja o que entra na seleção',
    sampleIntro: 'Uma edição ilustrativa para mostrar como o e-mail chega à sua caixa de entrada. A seleção muda todos os dias.',
    sampleAsideTitle: 'Bons links, em uma olhada.',
    sampleAsideDescription: 'Uma lista curta com a fonte e o assunto de cada matéria, para você escolher o que abrir.',
    sampleStamp: '23 SET',
    sampleEditionTitle: 'Tecnologia que vale o seu tempo.',
    sampleEditionDate: 'Quarta-feira, 23 de setembro de 2026',
    sampleEditionCount: '3 matérias selecionadas das últimas 24 horas',
    sampleArticleMeta: [
      'The Pragmatic Engineer · 22 set',
      'Simon Willison · 22 set · Modelos de IA',
      'SQLite · 23 set · Bancos de dados · Sistemas',
    ],
    sampleLeadTopic: 'Engenharia de software',
    sampleCurated: 'Seleção de João Coelho',
    sampleWebsite: 'Site',
    sampleUnsubscribe: 'Cancelar inscrição',
    processLabel: 'Como funciona', processTitle: 'Uma seleção antes de chegar até você',
    processIntro: 'O digest segue um caminho simples: de fontes confiáveis a um e-mail útil pela manhã.',
    steps: [
      { title: 'Buscar com amplitude', description: 'Feeds RSS e Atom selecionados são consultados ao longo do dia.' },
      { title: 'Ficar com o sinal', description: 'Os artigos são avaliados por relevância, e coberturas repetidas são removidas.' },
      { title: 'Enviar o essencial', description: 'Até oito links chegam juntos às 7h, horário de Brasília.' },
    ],
    finalLabel: 'O amanhã começa aqui', finalTitle: 'Menos busca. Mais descoberta.',
    finalDescription: 'Comece o dia com uma lista curta de ideias que valem a leitura.',
    finalAction: 'Receber a próxima edição',
  },
} as const;
