export type Locale = 'en' | 'pt-BR';

export const copy = {
  en: {
    language: 'Language',
    home: 'Home',
    eyebrow: 'An email for curious builders',
    title: 'A little less noise. A little more signal.',
    intro: 'Tech Digest brings together selected reading on software engineering and technology in a concise email.',
    detail: 'Interesting ideas, useful links, and context worth keeping. Straight to your inbox.',
    email: 'Email address',
    placeholder: 'you@example.com',
    subscribe: 'Subscribe',
    subscribing: 'Subscribing…',
    subscribeSuccess: 'You’re on the list. See you in your inbox.',
    invalidEmail: 'Enter a valid email address.',
    rateLimited: 'Too many attempts. Please try again later.',
    unavailable: 'The service is unavailable right now. Please try again later.',
    privacy: 'No account needed. Every email includes a link to unsubscribe.',
    from: 'A project by João Coelho',
    unsubscribeTitle: 'Stop receiving Tech Digest?',
    unsubscribeDetail: 'You can leave the list at any time.',
    confirm: 'Confirm unsubscribe',
    confirming: 'Unsubscribing…',
    unsubscribeSuccess: 'You’re unsubscribed. You won’t receive the next Tech Digest.',
    invalidToken: 'This unsubscribe link is not valid.',
    back: 'Back to Tech Digest',
  },
  'pt-BR': {
    language: 'Idioma',
    home: 'Início',
    eyebrow: 'Um e-mail para quem gosta de tecnologia',
    title: 'Menos ruído. Mais conteúdo que vale a leitura.',
    intro: 'O Tech Digest reúne leituras selecionadas sobre engenharia de software e tecnologia em um e-mail direto ao ponto.',
    detail: 'Ideias interessantes, links úteis e contexto para guardar. Direto na sua caixa de entrada.',
    email: 'Endereço de e-mail',
    placeholder: 'voce@exemplo.com',
    subscribe: 'Inscrever-se',
    subscribing: 'Inscrevendo…',
    subscribeSuccess: 'Inscrição confirmada. Até o próximo e-mail.',
    invalidEmail: 'Digite um endereço de e-mail válido.',
    rateLimited: 'Muitas tentativas. Tente novamente mais tarde.',
    unavailable: 'O serviço está indisponível agora. Tente novamente mais tarde.',
    privacy: 'Sem criar conta. Todo e-mail inclui um link para cancelar a inscrição.',
    from: 'Um projeto de João Coelho',
    unsubscribeTitle: 'Parar de receber o Tech Digest?',
    unsubscribeDetail: 'Você pode sair da lista a qualquer momento.',
    confirm: 'Confirmar cancelamento',
    confirming: 'Cancelando…',
    unsubscribeSuccess: 'Inscrição cancelada. Você não receberá o próximo Tech Digest.',
    invalidToken: 'Este link de cancelamento não é válido.',
    back: 'Voltar ao Tech Digest',
  },
} as const;
