export type Locale = 'en' | 'pt-BR';

export const copy = {
  en: {
    language: 'Language',
    home: 'Home',
    eyebrow: 'An email for curious builders',
    title: 'A little less noise. A little more signal',
    intro: 'Tech Digest brings together selected reading on software engineering and technology in a concise email.',
    detail: 'Interesting ideas, useful links, and context worth keeping. Straight to your inbox.',
    email: 'Email address',
    placeholder: 'you@example.com',
    subscribe: 'Subscribe',
    subscribing: 'Subscribing…',
    subscribeSuccess: 'You’re on the list. See you in your inbox.',
    invalidEmail: 'Enter a valid email address.',
    rateLimited: 'Too many attempts. Please try again later.',
    unavailable: 'The service is unavailable right now. Please try again later.',
    privacy: 'No account needed. Every email includes a link to unsubscribe.',
    from: 'A project by João Coelho',
    unsubscribeTitle: 'Stop receiving Tech Digest?',
    unsubscribeDetail: 'You can leave the list at any time.',
    confirm: 'Confirm unsubscribe',
    confirming: 'Unsubscribing…',
    unsubscribeSuccess: 'You’re unsubscribed. You won’t receive the next Tech Digest.',
    invalidToken: 'This unsubscribe link is not valid.',
    back: 'Back to Tech Digest',
    processLabel: 'The process',
    processTitle: 'How it works',
    processIntro: 'A small reading filter, from source to inbox.',
    steps: [
      { title: 'Collect', description: 'Selected RSS and Atom feeds are checked throughout the day.' },
      { title: 'Understand', description: 'Jev maps each article to a defined set of interests.' },
      { title: 'Rank', description: 'Python applies consistent weights and thresholds to those signals.' },
      { title: 'Deduplicate', description: 'Overlapping coverage is filtered before the final selection.' },
      { title: 'Deliver', description: 'Up to eight links arrive in one daily email.' },
    ],
    pipelineLabel: 'From source to inbox',
    pipeline: ['Selected sources', 'Content extraction', 'Jev classification', 'Deterministic scoring', 'Semantic deduplication', 'Up to 8', 'Email'],
    engineeringLabel: 'The decisions behind it',
    engineeringTitle: 'Under the hood',
    engineeringIntro: 'AI where it helps. Deterministic logic where it matters.',
    engineering: [
      { title: 'Structured signals', description: 'Jev / TypeSafe identifies interests; Python calculates the final relevance score.' },
      { title: 'Lean storage', description: 'Article text is used temporarily. SQLite keeps metadata and classification results.' },
      { title: 'Production delivery', description: 'Scheduled jobs run on Railway; Resend sends the email. The signup lives on Next.js and Vercel.' },
    ],
    sampleLabel: 'A look inside',
    sampleTitle: 'A sample edition',
    sampleIntro: 'Real links from monitored sources, arranged as an illustrative preview. Each day’s selection is different.',
    sampleWhy: 'Why',
    sampleRead: 'Read article',
    sampleReasons: ['Software engineering', 'AI models'],
    finalTitle: 'Get the next edition.',
    finalDescription: 'A short list of links worth opening, delivered to your inbox.',
    finalAction: 'Subscribe to Tech Digest',
  },
  'pt-BR': {
    language: 'Idioma',
    home: 'Início',
    eyebrow: 'Um e-mail para quem gosta de tecnologia',
    title: 'Menos ruído. Mais conteúdo que vale a leitura',
    intro: 'O Tech Digest reúne leituras selecionadas sobre engenharia de software e tecnologia em um e-mail direto ao ponto.',
    detail: 'Ideias interessantes, links úteis e contexto para guardar. Direto na sua caixa de entrada.',
    email: 'Endereço de e-mail',
    placeholder: 'voce@exemplo.com',
    subscribe: 'Inscrever-se',
    subscribing: 'Inscrevendo…',
    subscribeSuccess: 'Inscrição confirmada. Até o próximo e-mail.',
    invalidEmail: 'Digite um endereço de e-mail válido.',
    rateLimited: 'Muitas tentativas. Tente novamente mais tarde.',
    unavailable: 'O serviço está indisponível agora. Tente novamente mais tarde.',
    privacy: 'Sem criar conta. Todo e-mail inclui um link para cancelar a inscrição.',
    from: 'Um projeto de João Coelho',
    unsubscribeTitle: 'Parar de receber o Tech Digest?',
    unsubscribeDetail: 'Você pode sair da lista a qualquer momento.',
    confirm: 'Confirmar cancelamento',
    confirming: 'Cancelando…',
    unsubscribeSuccess: 'Inscrição cancelada. Você não receberá o próximo Tech Digest.',
    invalidToken: 'Este link de cancelamento não é válido.',
    back: 'Voltar ao Tech Digest',
    processLabel: 'O processo',
    processTitle: 'Como funciona',
    processIntro: 'Um filtro de leitura enxuto, das fontes até a sua caixa de entrada.',
    steps: [
      { title: 'Coletar', description: 'Feeds RSS e Atom selecionados são consultados ao longo do dia.' },
      { title: 'Entender', description: 'O Jev relaciona cada artigo a interesses definidos.' },
      { title: 'Ranquear', description: 'O Python aplica pesos e critérios consistentes a esses sinais.' },
      { title: 'Deduplicar', description: 'Coberturas repetidas são filtradas antes da seleção final.' },
      { title: 'Entregar', description: 'Até oito links chegam em um único e-mail diário.' },
    ],
    pipelineLabel: 'Das fontes ao e-mail',
    pipeline: ['Fontes selecionadas', 'Extração de conteúdo', 'Classificação com Jev', 'Pontuação determinística', 'Deduplicação semântica', 'Até 8', 'E-mail'],
    engineeringLabel: 'As decisões por trás',
    engineeringTitle: 'Por trás do Tech Digest',
    engineeringIntro: 'IA onde ajuda. Lógica determinística onde importa.',
    engineering: [
      { title: 'Sinais estruturados', description: 'Jev / TypeSafe identifica interesses; o Python calcula a relevância final.' },
      { title: 'Armazenamento enxuto', description: 'O texto do artigo é usado temporariamente. O SQLite guarda metadados e resultados da classificação.' },
      { title: 'Entrega em produção', description: 'Jobs agendados rodam no Railway; o Resend envia o e-mail. A inscrição usa Next.js e Vercel.' },
    ],
    sampleLabel: 'Por dentro',
    sampleTitle: 'Exemplo de edição',
    sampleIntro: 'Links reais de fontes monitoradas, organizados como prévia ilustrativa. A seleção muda a cada dia.',
    sampleWhy: 'Por que vale ler',
    sampleRead: 'Ler artigo',
    sampleReasons: ['Engenharia de software', 'Modelos de IA'],
    finalTitle: 'Receba a próxima edição.',
    finalDescription: 'Uma lista curta de links que valem a leitura, direto no seu e-mail.',
    finalAction: 'Inscrever-se no Tech Digest',
  },
} as const;
